services:
#    rest_auth.example:
#        class: Rest\AuthBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    create_client_form:
        class: Rest\AuthBundle\Form\Type\CreateClientFormType
        tags:
            - {name: form.type, alias: create_client}