test:
    resource: "@TestTestBundle/Resources/config/routing.yml"

rest_api:
    type: rest
    prefix:   /api/post
    resource: "@RestApiBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc