security:
    # providers:
    #     in_memory:
    #         memory: ~

    # firewalls:
    #     dev:
    #         pattern: ^/(_(profiler|wdt|error)|css|images|js)/
    #         security: false

    #     default:
    #         anonymous: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            # anonymous:  false # can be omitted as its default value   

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                invalidate_session: false
                target: /login
            anonymous:    true     
            
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false
            # Add your favorite authentication process here

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }         
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }         
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }