security:
    # providers:
    #     in_memory:
    #         memory: ~

    # firewalls:
    #     dev:
    #         pattern: ^/(_(profiler|wdt|error)|css|images|js)/
    #         security: false

    #     default:
    #         anonymous: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        # user_secured:
        #     name: user_security
        #     entity: { class: Rest\AuthBundle\Entity\User, property: username }

    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous: false

        # oauth_secured:
        #     pattern: ^/oauth
        #     provider: fos_userbundle
        #     http_basic: ~
        #     anonymous: false
        #     context: primary_auth

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: /login
                invalidate_session: false
            anonymous:    true
            # context: primary_auth

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false


    access_control:     
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }